### ISSUE TITLE
Make UseInstance obsolete in favor of Use and RegisterInstance

### ISSUE THREAD

**Issue by dadhi** [dadhi/DryIoc#232]

**Comment by detoxhby** [comment]
Tried to realize the real difference between `Use` and `RegisterInstance` based on [documentation](https://bitbucket.org/dadhi/dryioc/wiki/ReuseAndScopes.md), but there is not enough information about it.

Could you please provide an in-depth explanation of in which scenarios should each be used (and why)?

Thanks!

**Comment by dadhi** [comment]
`ReristerInstance` or `Register..` in general is supposeD to be done once when bootsrapping app / service. `Use` is for supplying the context data at runtime with each request / unit-of-work.
Previously `UseInstance` wads trying to do both, therefore it is much harder to implement.
`Use` now is much simplier but cannot be used with wrappers and decorators, meanwhile `RegisterInstance` is just another type of registration can be decorated, wrapped.

**Comment by detoxhby** [comment]
Thank you!

Based on your explanation, I got the intention of what's really behind of this concept-separation.
The only disturbing part is:
```csharp
container.RegisterInstance(service, Reuse.InCurrentScope);
```
which is effectively the same as
```csharp
scope.Use(service)
```

I think it would be cleaner & more intuitive to support only singleton reuse (without reuse parameter), because "_registering_" is static in sense of developer's intention.

On the other hand, to make decoration/wrappers supported, the internal _"special"_ encapsulator type should be made public and used just like how `Made`, `Reuse` and others are available, effectively changing/modifing the way the operation is done (without introducing another API).

For example:
```csharp
// current API stays the same
(ext) resolverContext.Use<TService>(TService instance);
resolverContext.Use(Type serviceType, object instance);

// NEW overloads based on `Instance` first parameter

// feels the same, but internally it's handled with `RegisteredInstanceFactory`
// will honor scope if available, otherwise falls back to singleton-scope
resolverContext.Use(Instance.Registered(service, IfAlreadyRegistered...);

// same API, registers into singleton scope even if current scope is available
resolverContext.Use(Instance.Singleton(service, IfAlreadyRegistered...);

// possible workaround for mid-part to support container-based current scope registrations
// will behave just like current RegisterInstance's logic: will throw if no current scope available
resolverContext.Use(Instance.Scoped(service, IfAlreadyRegistered...);
```

I know it's a big decision to change public API like that, but current pre 5.0 lifetime is ideal if you do so.

What are your thoughts?

**Comment by dadhi** [comment]
> The only disturbing part is: `container.RegisterInstance(service, Reuse.InCurrentScope);`

There is no parameter `reuse` in `RegisterInstance` in v4.1.

**Comment by detoxhby** [comment]
Alright, if you have time, please put a warning/info here [wiki/ReuseAndScopes.md](https://bitbucket.org/dadhi/dryioc/wiki/ReuseAndScopes.md) about 4.1 changes to clarify this.

**Comment by dadhi** [comment]
Will do, thanks for pointing.

**Comment by dadhi** [comment]
done
