### ISSUE TITLE
breaking changes in DryIoc.Microsoft.DependencyInjection 4.1.0

### ISSUE THREAD

**Issue by ssteiner** [dadhi/DryIoc#302]
Today I upgraded DryIoc to the latest version - from 4.2.4 to 4.3.0 and the MS Dependency injection from 4.0.0 to 4.1.0. Next I knew, my code wouldn't compile as

`DryIocAdapter.DryIocServiceProviderFactory`

no longer seems to exist. What would be the replacement?

**Comment by dadhi** [comment]
Fck, ok. I will return it back.

**Comment by dadhi** [comment]
@ssteiner Ok, it seems a more messy situation... 
I have moved `DryIocServiceProviderFactory` outside because of the rest of the types (e.g. `DryIocServiceScopeFactory` and `DryIocServiceScope` ) are also not nested and seemingly the  `DryIocServiceProviderFactory` was made nested by mistake.
The [sample](https://github.com/dadhi/DryIoc/blob/master/samples/DryIoc.AspNetCore31.WebApi.Sample/Program.cs) also relies on `DryIocServiceScopeFactory` to be **not-nested**.

Apparently som Users already adapted to this error (as expected) and are using the nested `DryIocServiceScopeFactory`.

So sorry, for confusion here - **Let's keep the `DryIocServiceScopeFactory` outside** to be at lease on the consistent side and to stop moving the target.

Please adjust your code accordingly.

Btw, I am not sure - should I release the current version as v5 and unlist the v4.1 from NuGet :(
Maybe will wait for other complaints.

**Comment by ssteiner** [comment]
If you strictly adhere to semantic versioning, I guess it needs to be v5.

I adapted my code and upgraded the 4.1.0 again :)

**Comment by dadhi** [comment]
@ssteiner 
DryIoc.Microsoft.DependencyInjection v5.0.0 is out.

https://github.com/dadhi/DryIoc/releases/tag/v4.5.0
