### ISSUE TITLE
None generic class implementing generic interface not registered

### ISSUE THREAD

**Issue by MikaelFerland** [dadhi/DryIoc#309]
I added the following public class in RegisterManyTests.cs :
`public class YetAnotherBlah : IBlah<string, int> { } `

Then I expected that it should be be resolved in 
`Can_register_generic_service_Only_with_its_implementations_found_in_assemblies()`

But it only resolved Blah and AnotherBlah.

**Comment by dadhi** [comment]
Thanks, will look.

**Comment by dadhi** [comment]
Check the [modification](https://github.com/dadhi/DryIoc/commit/0a25839743deab28329c85de1ef141ad3edea89f) I've done for the test to pass.

So in a way, the test actually does what its name says Can_register_**generic_service_Only**_with_its_implementations_found_in_assemblies.

Because the `YetAnotherBlah` is not a generic type, DryIoc does not attempt to check its open-generic interface, though technically this is fine.

The question, should I change this behavior - to make it check the open-generic types?
Because the change may subtly break already written code.
I am not sure, probably the provided workaround will be a more explicit solution.

**Comment by MikaelFerland** [comment]
Thank you for the modification.
It makes sense, maybe you should keep the actual implementation to avoid breaking the existing code.
I will keep in mind the provided workaround.

**Comment by dadhi** [comment]
Ok, closing then.
