### ISSUE TITLE
Why doesn't DryIocAttribute with a target of net45 use the System.ComponentModel.Composition NuGet package?

### ISSUE THREAD

**Issue by poruru-dev** [dadhi/DryIoc#335]
My project uses a attribute that inherits From System.ComponentModel.Composition.ExportAttribute.
This issue causes [CS0433](https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/compiler-messages/cs0433
).

**Comment by dadhi** [comment]
@poruru-dev This is unfortunate. I don't understand the refetenced issue because it is not in english.

How do your project reference the System.ComponentModel.Composition, via the [nuget package](https://www.nuget.org/packages/System.ComponentModel.Composition) or via the GAC assembly reference?
If it is via the nuget package I can add it back to the DryIocAttributes, it's likely removed by mistake.

**Comment by dadhi** [comment]
@poruru-dev  The fix v6.0.1 is out.
