### ISSUE TITLE
Diagnosing the infinite loop in WaitForItemIsSet method

### ISSUE THREAD

**Issue by yallie** [dadhi/DryIoc#375]
Hello Maksim,

Got this freeze after upgrading the app to DryIoc.dll v4.5.2:

![image](https://user-images.githubusercontent.com/672878/108555107-15f04d00-7306-11eb-90a1-c57f23282996.png)

The code being executed has a pretty complex dependency graph with dynamic registrations.
The lockup occurs randomly at different locations and doesn't seem to stable reproduce.
Sometimes the tests pass, and then freeze when run again for the second time right after that.

Any thoughts how to diagnose such issues?

I couldn't update to the latest DryIoc.dll v4.7.3 because MefAttributedModel.dll still references v4.5.2.
Perhaps upgrading to v4.7.3 is the first thing that should be done?

**Comment by dadhi** [comment]
> Perhaps upgrading to v4.7.3 is the first thing that should be done?

Yes, indeed.

**Comment by yallie** [comment]
Updated to v4.7.3, the issue is still there, but looks like it's somehow 
related to the missing current scope exception thrown when resolving a scoped service.
I get a missing scope exception, then the resolution loops in WaitForItemIsSet.
Once the missing scope error is fixed, the infinite loop doesn't occur anymore.

I still believe that's a bug somewhere, so please don't close this issue for a while.
I'll try to reproduce the issue.

**Comment by dadhi** [comment]
> I'll try to reproduce the issue.

Thanks, I would like to see more info before starting to dig.

**Comment by Havunen** [comment]
I have seen this same issue happen in our application. I think it occurs only if exception is thrown at some point during long graph service resolution. Fixing the exception fixed also the loop

**Comment by dadhi** [comment]
@Havunen, @yallie,

> I have seen this same issue happen in our application. I think it occurs only if an exception is thrown at some point during long graph service resolution. Fixing the exception fixed also the loop

It is good to hear but also it is bad in a way that hard to diagnose.
I am guessing that due to exception there is no way to signal for the waiting side (by setting the entry value).
So I would like to find a way to stop waiting in this situation.

- First thought is to use time-out for the waiting - and here the main question is to guess the suitable timeout value.
- Second thought is to find the exact problem place and set the entry to the special value on exception, e.g. `ItemCreationFailed` - and here the more work to handle this value without performance degradation.

**Comment by dadhi** [comment]
@Havunen Did you remember what the places causing the issue? I want (if possible) to minimize the scope of the fix.

**Comment by Havunen** [comment]
No, it was not a big deal for us because there was real error to fix and then that went away

**Comment by dadhi** [comment]
Should be fixed together with #391
