### ISSUE TITLE
Best way to achieve isolated service instance use

### ISSUE THREAD

**Issue by mpaul31** [dadhi/DryIoc#38]
I'm not sure what is the best way to achieve what I am trying to accomplish so let me give you an example.

I am using Azure Functions, which are stateless, with the following signature.

```
public static Task Run(Message message, ILogger logger)
{
    var controller = Main.Container.Resolve<CsoConsumerController>();

    // How can I attach the passed in logger instance so the rest of the services for the current flow re-use this instance?

    return controller.Execute(message);
}
```

As you can see, the azure function framework passes me an instance of the ILogger already configured and initialized for this function call **ONLY**.

I read through the documentation and I think I need a new scope here but I'm not sure. I only want this ILogger instance to be used during the async execution of this one method call. Each function call will use their own.

Any help would be great?

**Comment by mpaul31** [comment]
i tried to do something like this but i get the error "No current scope available"

Would this even work as I desire?

```public class ProxyLogger : ILogger
{
    public ILogger Logger { get; set; }

    public IDisposable BeginScope<TState>(TState state)
    {
        return Logger.BeginScope(state);
    }

    public bool IsEnabled(LogLevel logLevel)
    {
        return Logger.IsEnabled(logLevel);
    }

    public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
    {
        Logger.Log(logLevel, eventId, state, exception, formatter);
    }
}
```

```
public static Task Run(Message message, ILogger logger)
{
    var proxyLogger = Main.Container.Resolve<ProxyLogger>();

    proxyLogger.Logger = logger;

    var controller = Main.Container.Resolve<CsoConsumerController>();

    return controller.Execute(message);
}
```

**Comment by dadhi** [comment]
>i tried to do something like this but i get the error "No current scope available"

> Would this even work as I desire?

There are too many questions here:

- In order to resolve something with `Reuse.Scoped` yes, you need to `OpenScope`.
- Why do you have two registrations of `ProxyLogger` implementations? Is this suppose to be different instances?

Answering on the previous question:
> so using a scope here would not be the correct solution? is that because the instance has to be registered before the scope is created?

Generally, putting a run-time state (here is the `logger` parameter) into the container is a bad idea. For the sake of it, you may try to `OpenScope` and do `container.UseInstance(logger)`, then resolve consumer service under the scope, then at the end `Dispose` of scope. So for the sake of passing the argument to the function, you introduce a shared state, then dispose of it, maybe with traces remaining in the container (cache) forever. That's why I am not encouraging the `container.UseInstance`. There are very little places where you need it - usually, those are integrations with other IoC/DI abstractions which were designed this way.

Therefore, if you can go without `UseInstance` or putting the state into the container, please do.
I would suggest using an approach with `Func` or passing `args` to `Resolve`.

**Comment by mpaul31** [comment]
Thank you for the detailed response. unfortunately that is how azure functions work, they are stateless and pass the logger into the function as a parameter.

also i do not believe the func callback will work because there are many services in the call execution that will need a reference to the ILogger not just the controller.

with that said and hopefully i explained the scenario better, async scope is required since the function returns a Task correction?

**Comment by dadhi** [comment]
Then you may try to "register" `logger` to scope via `UseInstance`.

```cs
// somewhere where you create a container, specify the ambient scope context to scope being propagated across async / await call boundaries
Container = new Container(scopeContext: new AsyncExecutionFlowScopeContext());

public static Task Run(Message message, ILogger logger)
{
    using (var scope = Main.Container.OpenScope()) 
    {
      scope.UseInstance(logger);
      var controller = scope.Resolve<CsoConsumerController>();
      return controller.Execute(message);
    }  
}
```

Btw, I would still go with `Func<>` or `Resolve(...args: )` - cause how many resolution roots (`Resolve` calls) you have? Ideally, it should be a single one (e.g. `controller` in your case). Then resolving controller as `Func<ILogger, MyController,>` then calling the `Func` with `logger` will pass the logger to all nested dependencies, not only controller itself. You don't need multiple `Func`s or something.

**Comment by mpaul31** [comment]
> Btw, I would still go with Func<> or Resolve(...args: ) - cause how many resolution roots (Resolve calls) you have? Ideally, it should be a single one (e.g. controller in your case). Then resolving controller as Func<ILogger, MyController,> **then calling the Func with logger will pass the logger to all nested dependencies, not only controller itself.** You don't need multiple Funcs or something.

I see what you mean now thanks makes sense!!
